# This is a basic workflow to help you get started with Actions

name: image-sync
on:
  push:
    branches: [ calico ]
  pull_request:
    branches: [ calico ]
  schedule:
    - cron: '0 14 * * 1'

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        sudo apt install -y skopeo
        skopeo --version
        
    - name: skopeo login
      run: echo $PASSWORD | sudo skopeo login registry.cn-shenzhen.aliyuncs.com --username $USERNAME --password-stdin 

    - name: sync images
      run: skopeo sync --src yaml --dest docker sync.yaml registry.cn-shenzhen.aliyuncs.com/cnmirror
