name: image-sync
on:
  push:
    branches: [ rook ]
  pull_request:
    branches: [ rook ]
  schedule:
    - cron: '0 14 * * 1'

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: check podman
      run: |
        sudo podman version
    - name: sync images
      run: |
        sudo podman run -it --rm -v ${PWD}:/workspace -w /workspace quay.io/skopeo/stable:latest \
        sync --src yaml --dest docker sync.yaml registry.cn-shenzhen.aliyuncs.com/cnmirror \
        --dest-username $USERNAME --dest-password $PASSWORD \
        --keep-going --retry-times 2
