name: image-sync
on:
  push:
    branches: [ calico ]
  pull_request:
    branches: [ calico ]
  schedule:
    - cron: '0 14 * * 1'

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  image-sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        sudo apt install -y skopeo
        sudo skopeo --version

    - name: sync images
      run: sudo skopeo sync --src yaml --dest docker sync.yaml registry.cn-shenzhen.aliyuncs.com/cnmirror --dest-username $USERNAME --dest-password $PASSWORD
